### ISSUE TITLE
Spektra - Twitter Testing

### ISSUE THREAD

**Issue by daronyondem** [microsoft/Azure-Analytics-and-AI-Engagement#21]

**Comment by shashankkhedikar** [comment]
Task 7 
Activity: Subscription selection
Issue: Is there any way we can index these and then select index instead of Subscription name type. Sometimes subscription names are too long. If not copy paste will do.
![image](https://user-images.githubusercontent.com/10440963/88863996-05855300-d1b9-11ea-83d1-5954205eb21a.png)

Activity: Select Resource Group
Issue: Typo in Copy and paste* line
![image](https://user-images.githubusercontent.com/10440963/88864026-1a61e680-d1b9-11ea-8469-180f6ea5b58b.png)

Issue: 
![image](https://user-images.githubusercontent.com/10440963/88864047-264da880-d1b9-11ea-8b58-52b136100e2a.png)

**Comment by daronyondem** [comment]
Hi @shashankkhedikar 

- Subscription name copy past improvement needs to be submitted as a separate issue for prioritization.
- I don't see anything to fix related to Power BI Desktop/Datasets Connection. The document is pretty clear on that one. Isn't it?
- I'm not sure I understand what you are reporting about Task 10. I suggest you submit separate issues for separate problems so that we can assign those to their owners one by one.

I will close this issue now, hoping that you will report the remaining issues in separate submission in github.

Thanks
